### ISSUE TITLE
Design the UiGateway protocol

### ISSUE THREAD

**Issue by clandest** [MASQ-Project/MASQ-Node-issues#140]
The data protocol between the UI and the UiGateway, and between the UiGateway and the rest of the SubstratumNode, is pretty ad hoc at the moment. Come up with a design for it that will support future expansion, addressing the following concerns and any others that arise in the process:

Multiple UIs for the same Node that can connect and disconnect at any time and are kept in sync with each other: **Each UI has its own `client_id`, assigned by the Node. The UI never knows its `client_id`, but the Node uses it to keep them separated. Synchronization will depend on the message type.**

Minimal knowledge in the UiGateway of the responsibilities of other actors in the Node: **The UiGateway holds a list of actors that are willing to receive UI messages. Every UI message that comes in is broadcast to every one of these actors. If an actor doesn't understand a particular message, it ignores that message.**

Handling of Notifications (broadcast to all participating actors and/or UIs, no response): **All incoming messages are broadcast; outgoing messages can either have a `MessageTarget::ClientId(n)`, where `n` is the ID of the target client, or a `MessageTarget::AllClients`, in which case it will be broadcast to all clients. Notifications on the wire will have no `contextId` field; in memory they'll have a `path` field set to `MessagePath::OneWay`.**

Handling of Commands (intended for a single target (although perhaps broadcast to everyone and ignored by all but the target), producing a small success-or-failure-reason response): **No difference currently between Commands and Queries.**

Handling of Queries (intended for a single target, probably producing a large and complex response): **No difference currently between Commands and Queries.**

**Both Commands and Queries will, on the wire, have a `contextId` field with a numeric value. This will serve to identify the particular conversation, and connect request with response. That is, if a request from the UI with `client_id` 1234 has `contextId` of 94387245, then the response to that request that goes out to the UI with `client_id` 1234 will also have a `contextId` of 94387245. This will allow the UI to link a response to a particular outstanding request, even if there are many simultaneous outstanding requests of the same type. In memory, Commands and Queries will have a `path` field set to `MessagePath::TwoWay(contextId)`.**

**Commands and Queries should have a `payload` field containing a JSON object with the parameters of the message in it. The response to a Command or Query can have either a `payload` field or an `error` field; if the `error` field is present, it will have `code` and `message` subfields, where the `code` is a numeric value unique to that kind of error, and the `message` describes the error suitably for display to the user.**

Decide whether the steady-state protocol should be fundamentally client-server (like HTTP) or symmetric (like TLS): **Symmetric on the wire; off the wire, mostly symmetric except that incoming messages always have a single `client_id`, and outgoing messages can be broadcast. UIs only ever converse with the server, never with each other.**

**Comment by dnwiebe** [comment]
Suggested test plan (assuming you have `websocat` installed on your system):

First, start the Node in zero-hop mode with logging turned all the way up; something like this:

`sudo MASQNode --dns-servers 1.1.1.1 --log-level trace --neighborhood-mode zero-hop`

Then, in another terminal window, start `websocat` in client mode and connect it to the Node, using protocol `MASQNode-UIv2` on port 5333:

`websocat --text --protocol MASQNode-UIv2 ws://127.0.0.1:5333`

Now type some JSON into `websocat` and watch to see how the Node handles it. So far, one of the only two messages in `MASQNode-UIv2` that the Node understands is the "financials" message:

```
{
    "opcode": "financials",
    "contextId": 1234,
    "payload": {
        "payableMinimumAmount": 100,
        "payableMaximumAge": 86400,
        "receivableMinimumAmount": 100,
        "receivableMaximumAge": 86400
    }
}
```

The value of the `contextId` field doesn't matter, but it must be present, numeric, and nonnegative.

xxx`MinimumAmount` means that you don't want to see any payable or receivable accounts that have balances smaller than this number. xxx`MaximumAge` means that you don't want to see any payable or receivable accounts that have balances older than this number in seconds. (86400 is one day.)

The response should look something like this (remember, in JSON the order of fields in an object doesn't matter):

```
{
    "opcode": "financials",
    "contextId": 1234,
    "payload": {
        "payables": [
            {
                "wallet": "0x0c080400e31b727636248090650A197c495E4787",
                "age": 9284,
                "amount": 2375623,
                "pendingTransaction": "0xf0ecfa69d94a722e6ec5e7b6f61bd9f7b66472847bd0e240257c1c2646a17478",
            },
            {
                "wallet": "0x3153509c7B698e6577934B19069d6dE39a6c227d",
                "age": 54838,
                "amount": 63642
            }
        ],
        "receivables": [
            {
                "wallet": "0x00b8B059F132009E5a812F27cc42733d135915df",
                "age": 62873,
                "amount": 2743
            }
        ],
        "totalPayable": 3006374,
        "totalReceivable": 2743
    }
}
```

The `contextId` field in the response must have the same value you put in the `contextId` field of the request.

The `payables` and `receivables` records should match your database (which you can explore with `sqlite3`, which you'll probably want to install anyway if you don't already have it) subject to the constraints you specified in the request. The records should be sorted by decreasing balance and then increasing age. The `totalPayables` and `totalReceivables` fields should contain totals that include everything in the table, not just the records that make it past the minimum-amount and maximum-age filters.

The other message the Node kind of understands is the "shutdownOrder" message. The actual shutdown machinery is not implemented yet, but the Node receives and interprets the message and should produce an INFO log to that effect. The message should look like this:

```
{
    "opcode": "shutdownOrder",
    "payload": {}
}
```

Note that the `payload` is empty, but it must still be specified. Also note the absence of a `contextId` field: this is because "shutdownOrder" is a Notification that produces no response, so a `contextId` would be of no use. You can provide one if you like, but it will be ignored.

Furthermore, you should be able to send in anything you want using `websocat`, whether valid JSON or not, and A) not be able to crash the Node, and B) get some kind of useful message in the log about what was wrong with your input.  Don't just try bad JSON, though: try leaving fields out, try inventing new fields, try negative numbers, try ridiculously huge numbers, try strings or Boolean values in place of numbers and vice versa, or numbers in place of arrays, etc. etc.
