### ISSUE TITLE
Add Process Documentation

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#147]
Add CADENCE.md to the codebase, describing our iteration cadence, leaving out specifics to be determined later.

Add COLUMNS.md to the codebase, describing the meanings of each of the columns on the card wall, and including a definition of Done.

Add PRACTICE.md to the codebase, describing the engineering practices that will be expected of contributing developers.

**Comment by kauri-hero** [comment]
i will review this and provide some information that may help in the documentation.

**Comment by kauri-hero** [comment]
Just a few things I noticed - the columns document still references the column "Done Since Standup", which we have made redundant for the time being (we aren't regularly having multiple people performing standups yet).
If you want to comment out that section for now until we put that column back on the board, then go ahead @dnwiebe
