### ISSUE TITLE
Design UI Gateway Protocol

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/MASQ-Node-issues#202]
**Pairing Card
@dnwiebe construct proposal to discuss with team.

"Design next level up layer above Websockets - how this will interact Node"

**Comment by dnwiebe** [comment]
### **UI-to-Node communication types**
**Connect UI/Handle Redirect**
**Fire-and-forget command from UI to Node**
	ShutdownMessage: `masq stop`
**Request-and-response from UI to Node, then back**
	SetGasPrice/SetGasPriceResponse: masq set gas-price 100, `masq show
		gas-price`
	SetDbPassword/SetDbPasswordResponse `masq set db-password "booga booga"`, or
		`masq set db-password` and then type password at console without echo
	GetNodeDescriptor/NodeDescriptor `masq show node-descriptor`
**Subscribe/Unsubscribe command from UI to Node**
	GetFinancialStatisticsMessage, unsubscribe version: `masq subscribe
		financials`
	GetNeighborhoodDotGraphRequest, unsubscribe version: `masq subscribe
		neighborhood`
**SubscribedData command from Node to UI**
	FinancialStatisticsResponse
	NeighborhoodDotGraphResponse
**Prompt from Node to UI to ask user for data**
	Maybe something like: `masq respond`, whereupon the CLI would come up, pull
		down all the waiting prompts, and present them for satisfaction one
		after another until gone?


### Pieces:
**1. `masqd`,** containing the entire code for Node, running with privilege, but only
	with a small portion of itself active. Comes up and opens no ports except a
	baby UIGateway on a well-defined port (5333, for example). Keeps a cache of
	information: either information about the active Node, or--if no active
	Node--a notification to that effect. Eventually it may be called upon to 
	start multiple simultaneous Nodes. Not anytime soon, but this capability 
	should not be designed away. When a UI connects to its UIGateway,
	if there is an active Node, the daemon redirects the UI to that Node. If
	there is not, no redirection takes place, but the number of commands that 
	can be accepted is limited to the `start` command and possibly some
	configuration commands.

**2. `masqd`,** forked from the daemon. Runs briefly with privilege, long enough to 
	open low ports, then discards privilege. Holds open a random UI port on 
	which to receive redirected UI connections. Otherwise, performs all the 
	normal Node functions.

**3. `masq`,** the CLI. Works in two modes:

**3a. Non-interactive mode:** Whenever a command is typed, the CLI comes up, makes 
	contact with `masqd` on port 5333 (or whatever), executes redirect if so 
	directed, and then translates and transmits the command from the command 
	line. If the command is fire-and-forget, shuts down immediately. If the command is
	request-and-response, waits for and displays response, then shuts down. If the
	command is subscribe, subscribes to a topic, receives and displays that topic until
	a SIGTERM is received, then sends an unsubscribe and terminates.

**3b. Interactive mode:** The user just types `masq` and presses Enter. The CLI comes
	up, establishes contact (and perhaps executes the redirect), prints its own
	command prompt (perhaps '`> `'), and waits. The user then proceeds to type a
	series of commands very much like the ones in non-interactive mode except
	that they don't have to begin with `masq`. Also, push notifications from
	Node can be preemptively displayed in interactive mode without waiting for 
	`masq respond` or anything similar.


### Cards to write:
* Invent yet another execution mode, along with --generate-wallet and 
	--dump-config and the rest, where the Node comes up, opens a small
	UIGateway, and listens for connections on a well-defined port (probably 
	5333). (This will eventually be the only way to start the Node, but to 
	keep it in service as these changes are made, this should start out as an 
	additional mode of operation.) When the connection is made:
	
	if a daemon has already been forked, with a secondary UI port, and is 
			still running:
		Respond to any traffic across the connection with an instruction to 
				redirect to the secondary UI port
	else
		if a 'start' command arrives:
			Fork the Node as a daemon in standard mode, passing on all the 
					start parameters and specifying a free UI port.
		else if some other command arrives:
			Reject it.
If the format of the Shutdown command changes, make sure the forked daemon can
	still handle it. This card should include adding the capability to receive
	fire-and-forget commands from a UI.

* Add another codebase to the project, the CLI. Make it capable of connecting
	to the UIGateway, of following a redirect, and of sending 'start' and
	'shutdown' commands.

* Make the CLI capable of both noninteractive and interactive operation.

* When the Node process starts under Linux, have it daemonize itself. When it 
	forks, have the fork daemonize again. Rename the Linux executable to masqd.

* When the Node process starts under macOS, have it daemonize itself. When it 
	forks, have the fork daemonize again. Rename the macOS executable to masqd.

* Make the Windows Node process a system service. Windows doesn't fork, and 
	always runs as Administrator anyway, so privilege isn't as important.

* Enhance the CLI and the Node to be able to handle the 
	GetFinancialStatistics/FinancialStatisticsResponse messages, or their 
	replacements.

* Enhance the CLI and the Node to be able to handle the 
	GetNeighborhoodDotGraphRequest/NeighborhoodDotGraphResponse messages, or 
	their replacements.

* Enhance the CLI and the Node to be able to handle the 
	SetGasPrice/SetGasPriceResponse messages, or their replacements.

* Enhance the CLI and the Node to be able to handle the 
	SetDbPassword/SetDbPasswordResponse messages, or their replacements.

* Enhance the CLI and the Node to be able to handle the 
	GetNodeDescriptor/NodeDescriptor messages, or their replacements.

* Enhance the CLI and the Node so that --generate-wallet can be done via the 
	CLI.

* Enhance the CLI and the Node so that --recover-wallet can be done via the 
	CLI.

* Enhance the CLI and the Node so that --dump-config can be done via the 
	CLI.

* Remove the --generate-wallet, --recover-wallet, --dump-config, and standard 
	modes for the Node, and make the daemon mode the only one available.

* Modify TNT to use the CLI instead of directly starting the Node itself.
