### ISSUE TITLE
Special-case the db-password in masq

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#302]
Currently, the `db-password` and `consuming-private-key` parameters are treated by `masq` just like any other parameter, which means that they're displayed in the `setup` parameter dump for everyone to see.

Special-case the handling of `db-password` and `consuming-private-key` in `masq` so that they are never displayed. (Or, for extra credit, expand the protocol between the Daemon and `masq` so that the Daemon can direct `masq` not to display them.)

**Comment by bertllll** [comment]
If CLI stays considered as a permanent solution provided from MASQ besides the future GUI, and a user will always have a choice between both of them:

Narrowly related to this card, I think it is worth it improving the alignment of the long asterisk line for the "consuming-private-key" parameter. I already suggested it should remain 64 characters long, however the blank space between it and the third column should correspond to the minimal blank space which is seen on the left side (before the line starts).

This is a matter of perceiving general esthetic.
---------------------------------------------------------------------------------------------------------------------------------------------

The other issue is quite systemic, unfortunately. 

We have implemented a coverage for the sensitive passwords, however if it is meant seriously enough, it must be called ineffective. I think so since the sensitive data is also displayed and permanently printed into the console in the process of suppling these parameters.

I don't see quite elegant way out. My only suggestion of solution is to make these two (or maybe just db-password) go through two steps to set them up. I come from the fact there are no defaults for these, which we can take use of. 

1. step: A user is supposed to type just: (masq) setup --db-password
which will move him to another line, where the input is treated differently. Here all you type is hidden form people looking at the screen.

2. step: The user just will type in his password and press Enter

**Comment by bertllll** [comment]
If CLI stays considered as a permanent solution provided from MASQ besides the future GUI, and a user will always have a choice between both of them:

Narrowly related to this card, I think it is worth it improving the alignment of the long asterisk line for the "consuming-private-key" parameter. I already suggested it should remain 64 characters long, however the blank space between it and the third column should correspond to the minimal blank space which is seen on the left side (before the line starts).

This is a matter of perceiving general esthetic.
/-------------------------------------------------------------------------------------------------------------------------------------------

The other issue is quite systemic, unfortunately.

We have implemented a coverage for the sensitive passwords, however if it is meant seriously enough, it must be called ineffective. I think so since the sensitive data is also displayed and permanently printed into the console in the process of suppling these parameters.

I don't see quite elegant way out. My only suggestion of solution is to make these two (or maybe just db-password) go through two steps to set them up. Based on the fact there are no defaults for these, we can take use of it.

1st step: A user is supposed to type just: (masq) setup --db-password
which will move him to another line, where the input is treated differently. Here all you type is hidden from people looking at the screen.

2nd step: The user just will type in his password and press Enter
