### ISSUE TITLE
Partial panic

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#305]
If you start the Node in `originate-only` mode (or perhaps any mode, I don't know) and supply a `--neighbors` value that has only a public key and no IP address or clandestine port (that is, ends in either `@:` (for mainnet) or `::` (for ropsten), the Node will panic but stay running.

The Node should never panic and stay running under any circumstances. The no-IP/no-port neighbor should be detected during configuration validation and rejected.

Warning: do not fix this problem by preemptively checking for the particular combination of parameters above and terminating gracefully if it is detected. Instead, fix this problem by finding out why a panic in a background thread doesn't kill the Node completely, and fix the code so that it _does_ kill the Node completely.

**Comment by bertllll** [comment]
**Test plan:**

The biggest priority here takes the effort to prevent Node from hanging up as the whole process while its part has panicked and has been dead. It can technically happen because there are so called actors which are autonomous threads doing their business separately still communicating with other actors intensively with messages. 

Here we got a warning that panic in one actor (in total approx. 10) might not kill the whole app. It was believed from the deep past that this wouldn't happen. 

You can send crash messages, it is a testing tool and we should be careful with it because it shouldn't get in the knowledge of the end user. I think it will be made hidden eventually. 

So you need to do `setup --crash-point message` and start the Node (doesn't matter what the rest of the setting is - even the 'neighborhood mode') then do this command `crash <name-of-actor>`. It should work also as 'crash' only, used with a default. Sadly, this isn't really true, because I've determined an issue with sending this crash message as the first of first. It won't work, I wrote a card for it; but this concerns just a very specific types of messages which the user almost cannot encounter so solving it can wait awhile. To overcome that you just need to type whatever command you like first (that is devoted to the Node) and then you can finally send your crash request. Now it's going to be transmitted successfully.   
    
We're interested in `crash Neighborhood` the most, but if you want to play, feel free to type in for some other. You may be disappointed though with the results will seem the same. **Just remember, the process with Node should terminate fully, giving you the prompt on the command line back.**   

There is another behavior to test. That's what happens when an incomplete descriptor is given to the Node for the '--neighbors' parameter. Incomplete means a missing ip address and ports. 

Because this card goes before the new L2 descriptor notation sees the world it would look the old way, like this: 

`gBviQbjOS3e5ReFQCvIhUM3i02d1zPleo1iXg0EN6zQ::` for a test net and `gBviQbjOS3e5ReFQCvIhUM3i02d1zPleo1iXg/EN6zQ@:` for the mainnet.

You should not see a message about the public key - the beginning - if so, try to modify the key because it isn't being valid in the form it has, but you should be told that you cannot connect with a descriptor not containing a proper internet protocol address (IP).

You should also try if it's all right when the descriptors are complete.
