### ISSUE TITLE
Correct Gas Price Limits

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#396]
Currently, the gas price is limited to be between 1 and 99 gwei. This is inappropriate, because currently gas prices can rise much higher than 99 gwei.

Already, gas prices are between 100 and 500 gwei; it's debatable whether limiting gas prices is a good idea at all.

Consult with folks who have good experience with Ethereum, determine whether limits are a good idea and if so what they would be, and implement them instead of 1-99.

**Comment by kauri-hero** [comment]
There were some great comments @dnwiebe made in Telegram, so I want to add them here for use with this card, for future functionality of gas-prices across the BlockchainBridge:

> If I remember correctly, somebody may have been concerned that a user would accidentally fumble-finger an extra digit or two into the gas price and end up having the Node automatically pay more gas than intended by an order of magnitude or more until manual intervention. If gas prices are almost always going to be set by the GUI, that concern may evaporate.

> It's interesting to think about how one might design a gas-price UI to give the user access to the entire fifty-some bits of gas-price freedom while protecting him from accidentally specifying something too big. Maybe something like, "You're increasing the gas price by more than a factor of ten. Are you sure?" But I'm not a UX guy: I should probably shut up.
Rather than depending on a centralized service, there might be something the BlockchainBridge could do as it's doing its standard job of scanning the blockchain for transactions. Maybe it could capture the range of gas prices it's currently seeing on the blockchain and report it to the GUI somehow.  Or maybe that low/medium/high setting from the GUI could mean, "Low: pay the same gas as the cheapest transaction you find on the next scan. High: pay the same gas as the most expensive transaction you find on the next scan. Medium: pay gas midway between the cheapest and most expensive transactions you find on the next scan." Then the gas_price in the database configuration would change with each scan (or perhaps the structure of the gas-price configuration would change) and have the change be reported to all the UIs with a MASQNode-UIv2 message.
