### ISSUE TITLE
Unfork from the Substratum repository

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#417]
Now that the SubstratumNetwork GitHub account has been deleted, we should be able to unfork the Node repository without ethical issues.

Unfork the repo according to instructions here or elsewhere:

https://nickymeuleman.netlify.app/blog/unfork-github-repo

**Comment by masqrauder** [comment]
This is an operation a repository administrator will have to complete.

Note (from the link @dnwiebe included): 
> Since this is technically a brand new repository, some things (specific to the GitHub web UI) were lost. For example: pull requests, a description, the provided website url.

- This will mean that open PRs will have to be either merged or potentially recreated in the new repo.
- Issues will need to be re-linked to references or commits in the new repository if pointing to the old repository. The past commits should have the same hash but the repo name pointing to the renamed name may have to changed back to the original name.
- Downstream forks on disk may not notice any difference as the original name will be the same as before and their upstream remotes will be unchanged. Forks in GitHub may point to the old repo/new name. Worst case: downstream forks might have to be recreated on GitHub.
- I recommend retaining the old repository and placing it into Archived status to prevent inadvertent changes.
  - I don't know if a repo can be imported if it has been archived. If so, placing in Archived status first will prevent unexpected changes from individuals unaware during the renaming process.
  - Retain because old pull requests may need to be consulted.
  - If things go badly the imported repo can be deleted and the renaming can be undone back to the original name.
- Update the description on the imported repo from the old one.
- Update the website URL on the imported repo from the old one.
