### ISSUE TITLE
Try to figure out why the proper workspace.xml doesn't get generated automatically in Intellij or give better guidance to new contributors

### ISSUE THREAD

**Issue by bertllll** [MASQ-Project/MASQ-Node-issues#423]
As Firesteels rightly suggested, we could help people interested in contributing from a lot of troubles if they had a chance to read of the workspace.xml file somewhere here, which is needed to get Cargo working properly for the project.

**Comment by masqrauder** [comment]
Workspace.xml contains developer workspace specifics and should not be committed to the repo. Differences in settings will appear as constant churn and pulling changes will change your settings from those committed by someone else.

Perhaps instead we need to document how to properly use **New Project from Existing Sources....** in order to get setup as a developer on the project.

https://github.com/MASQ-Project/Node/blob/master/.gitignore#L47-L83 shows all the files that are deliberately excluded from the repo in the .gitignore file for good reason.
