### ISSUE TITLE
Update MASQNode-UIv2 Interface messaging

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/MASQ-Node-issues#466]
UPDATE - @bertllll 

This card can be split into smaller cards if necessary, but as a user of the UI, we want the websockets messaging to be able to deliver more information to the UI.

Update the configuration (see [current](https://github.com/MASQ-Project/Node/blob/master/USER-INTERFACE-INTERFACE.md#configuration-2) messaging to include the following values:

blockchain-service-url
automap protocol value (optional, if saved from a successful automap run)

--------------------------

Consider more messages and information that we desire to be sent over the UIGateway, so UI can display to user

This card should be played by a member of the UI team, and result in a nest of additional cards for the individual messages required.

Work will also likely be in the websockets message `configuration`

UX
Network display
Error handling - especially when db is corrupt; also Node crash on startup
Public-IP and Port-forwarding failures
Warn and Error-level logs

**Comment by bertllll** [comment]
Hi gyus @anonmate @kauri-hero, I follow your intentions but I need more specific info to the respective points you brought up here. They often mean a huge effort and such a case needs thorough description. 

First of all, the part above the horizontal line is almost behind us; GH-478 cares of blockchain-service-url and Dan's GH-372 will deliver a fully working `mapping protocol` value. 

So I'm naturally more interested in points below the line.

- UX - stated like this it will tell almost nothing to me - I need an assignment with concrete requirements, ideally proceeding from your strong needs for the user.

- What is network display? I almost cannot imagine what you mean.

- Node's error handling so that an error message travels to the UI, so we not only read from logs, is a huge thing, it will be one of milestones. But it could be done for sure. Still I'd like to hear more about what your idea is, we can adjust our ideas upon yours. 

- Public-IP, I don't understand the goal or scope of this, can you explain further?

- port forwarding failures has been taken care of along the automap development; the problem is that at the moment it ends up as with every other serious error in the Node - it crashes and prints a panic into the log file. So you see that to have these errors well served it would have to be played together with the third point of general error handling.     

- could be done but I'd like to hear why or some additional information; it would enormously help me with the eventual design

Of course I don't expect all these points answered at once but please if you'd like some of these to come true remember that it will need some additional description, ideally inside a separate card
