### ISSUE TITLE
Addition of CONFIG values written to database

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/MASQ-Node-issues#478]
Additional parameter values are needed to be stored in the database, so they can persist when Node shuts down.

From team discussion:

- Blockchain service URL should absolutely be stored in the database, and absolutely isn't now. That would be an excellent one to add.

- Chain ID should be stored as well, and there's a card in play right now to store it.
Reference #479 as it related to the chain indexing and addition of Polygon networks

- Neighborhood mode: you mean the default neighborhood mode that's used most times, with the option to use a different one next time it starts? Sure, I can see how that would be a good idea.

- Consuming private key: Yes, we can store it, but there's some design work to do there, since there's a denormalization problem there, what with consuming private key on the one hand and seed/derivation path on the other.
Reference #477 as it relates to this value being conditional on seedwords or single consuming-private-key value by itself

**Comment by bertllll** [comment]
Test plan

In the following text I'm going to speak of adding existing parameters into the database so that we can query them (not only) during the runtime. (It probably doesn't necessary have to to do with a human who is interested in the data but also some functions of the software or the UI needing the values for some reason).

Although one value had come in the database with a previous card, I had to fix it so that the parameter, it was a `chain name` (or simply chain), could correctly display with the `configuration` command. Given that I'd like to include a check of the repair I made in this card. 

Fully new members for in-database parameters are `neighborhood mode` and `blockchain service url`. Both should be tested thoroughly. 

_If you can to check that migration from an old DB version works, I'd appreciate it. But it's not necessary. (You could check that you migrated and after that your database already contains some value for `neighborhood-mode` but no for `blockchain service url`, in other words, the former value is ever populated)
The I stated here can be applied also on creation of a brand new DB, the result should be very similar (though some values of your old database should be taken over by the new version - which is why we have migrations. But I don't think you have to be cautious about this detail; it has been probably confirmed by the previous tests having also this theme)._

You should not omit:

- use both `MASQNode --dump-config` and `masq configuration` to see what your database stores in; my rule is that both output should always give you the same information (values must be identical with both, the number of displayed parameters should be too)
- in sake of deep observation, you may want to experiment and set (or modify) these new parameters and see if it writes into the DB
(Preventing confusion, which I don't think is actually threatening here: when you're manipulating the setup command the parameters you're after are called as follows --chain, --blockchain-service-url, --neighborhood-mode) 
- I'm not sure how to test this another thing but there is a rule that a value coming directly from the "user's hands" which I mean to be either the command line, a configuration file or environment variables, all such values should override stored in the DB. 
However if there is nothing of this kind available then the software reaches the database and takes the value from there; it is used as the last instance though. 
This rule has been a long time with us and it's not an invention of this card but I'm generally obligated (to exceptions) to sustain this behavior for all parameters that meet the database.   
- you should not see any panics of course so please report if you do (there could be one with `--dump-config` if the DB is nonexistent at the time of your attempt, which you can also test...for example by moving your database temporarily to a different location. See the next paragraph)
- so if there is a void from a certain chain database and you require to see its dump with `--dump-config` you will get a message that you cannot continue this way; the novelty is that the database is going to be created at the first time the Node is running, or at least it's my plan. The reason is that I'm trying to protect us from undefined behavior or extensive coding for all possible future migrations of our databases. I don't want let the code inflate this way and at this place, the periphery, so I've given all the power to the Node's own agenda which makes sense to me because Node is the very source of all our effort.
- similarly, the Daemon doesn't have a power to migrate the database. I designed it hopefully elegantly because I picked up on what had already existed and added my lines, declaring that if a database migration is detected as required the Daemon should behave as if there was no database to draw configuration out from, ignoring it. It's again a prevention of complicated database migrations which should not be a responsibility of the Daemon. We don't want Daemon to become overly wise. 

I theoretically could've forgotten to mention a thing or two; it's complicated to scribble a wholly description - also for me the more.
