### ISSUE TITLE
Make past-neighbors configurable in zero-hop mode

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#548]
Currently, past-neighbors cannot be configured in zero-hop mode, because zero-hop Nodes have no neighbors and no network for neighbors to occupy.

However, the GUI team has a requirement for configuring the Node database before actually starting a real network Node for the first time, and they've chosen to do this by starting a zero-hop Node and using its command-line parameters to set up the database.

Therefore they need the zero-hop restrictions against having --past-neighbors on the command line removed, and they need --past-neighbors on the command line to immediately set past neighbors in the database, rather than waiting until confirmation from the Debut process on the network, since there is no network in zero-hop mode.

**Comment by bertllll** [comment]
Test plan,

This is simple, just please consider two factors that we pursuit in this test.

A) Node running as 'zero-hop'
B) Node descriptors (one may be enough) supplied on the command line 

You should be able to see when you check your database (probably 'configuration' command) that before the test the neighbors are not saved inside but after you will have them in. 

You can also test what happens if you supply some invalid descriptors. 

Thank you
