### ISSUE TITLE
Insufficient balance check at scan time

### ISSUE THREAD

**Issue by bertllll** [MASQ-Project/MASQ-Node-issues#554]
**_This pertains to checking the balances of the ERC20 token (MASQ or testnet MASQ)_**

This is very desirable. As one of a few blockchain transaction related issues we can prevent, we should add a simple check done by using the web3 API to query information about current balance status of our consuming wallet. Specifically, there is a method in the `Eth` module which serves well to this purpose,  `.balance()`. I've tested it in a spike and all good.  

This should happen closely before sending the transaction, when we're processing a qualified payable account, and if we find out that the balance is lower than the planned payment we should abort with a warning log or later this information should get straightly to the user and his UI. 

Otherwise, if the check was okay, just let the transacting business happen.

**Comment by utkarshg6** [comment]
I'd like to share some of the research I did on this issue:

According to my understanding, the implementation in web3 will look very similar to the one mentioned in this answer - https://ethereum.stackexchange.com/questions/82746/how-to-get-erc20-token-balance-using-web3

We'll just need to find a way out to implement it using Rust's web3 library. Here's the link to the struct Contract, as mentioned in the above answer - https://docs.rs/web3/latest/web3/contract/struct.Contract.html

**Comment by kauri-hero** [comment]
This would definitely be a good idea, and ideally this would be built in across the UI messaging, so a websockets message could be sent to the UIs informing of a low or insufficient balance of MASQ/gas token

**Comment by bertllll** [comment]
I happened to discover an interesting fact: we had had a method to do the check before I wrote this card. So the implementation is going to be pretty easy now. 

Addition information that's good to know: 

Currently the output resulting from the event probably looks as follows.

First we get this message:
_ERROR: Accountant: Pending transaction '0x4108…78ad' announced as a failure, interpreting attempt 1 after 598990ms from the sending_

And just after it there is this one:
_WARN: Accountant: Broken transaction 0x4108…78ad left with an error mark; you should take over the care of this transaction to make sure your debts will be paid..._

Introduce surely a new, specific message in this moment but alongside you should also fix the mentioned messages so that they don't say just a partial piece of information about the transaction's hash. I experienced reading the logs and it really doesn't work like this - we need the whole piece of it. (Technically just make it printed within the Debug mode). Sensitivity of the information about the hash must be treated with different tools; maybe DB encryption?

**Comment by dnwiebe** [comment]
There should be a discussion about the frequency of this check. Remember, in clandestine mode the user will have to pay for all traffic to be routed, including traffic to the blockchain client. Consulting the blockchain before sending each CORES package will mean sending a CORES package before sending each CORES package, which--aside from the increased latency and increased cost--is impossible.

Suggestion: there should be a regular interaction with the blockchain (use `notify_later()` to some actor--perhaps the `BlockchainBridge`?--to schedule it) to check the consuming-wallet balance every few minutes or every hour or whatever turns out to be appropriate; this interaction should update a running balance that's kept in memory, checked every time sending a CORES package is contemplated, and updated every time a CORES package is sent.

This would be only approximately accurate, since when the Node comes up there are almost certainly already outstanding payables that haven't yet been collected; however, unlike the before-every-CORES-package scheme, it's possible.

It would mean that when money is added to the consuming wallet (either manually or because it's also the earning wallet), there would most likely be a delay before the balance increase was noticed by Node, and if the balance was allowed to drop too low, some inappropriate warnings might be generated.

**Comment by dnwiebe** [comment]
There should also be a discussion about what should happen when the consuming-wallet balance drops too low. Currently, ERROR and WARN logs are written, which will be broadcast across the `UIGateway` to the UIs (according to the code, every log of severity INFO or higher is broadcast). Is that enough, or do we need a special bespoke UI message for this?

What if there is no money at all in the consuming wallet? Do we simply warn the user, or do we stop him from transacting? (Remember, when a new user first brings up the Node, especially in a country where cryptocurrency is banned, he's going to have nothing in his consuming wallet and no way to get anything in there except by consuming routing and exit services from the Network to talk to a blockchain client.) How often do we warn the user? With every single CORES package? That's a lot. Only when the situation changes? That might not be enough, especially if the user isn't at the machine when the condition is detected.
