### ISSUE TITLE
Running out of gas

### ISSUE THREAD

**Issue by bertllll** [MASQ-Project/MASQ-Node-issues#555]
There is a chance, unless we introduce restrictions, that somebody could configure the gas price parameter as inadequately low that the transaction which will be sent out will stay pending as long as it has any gas remaining within its gas limit. (We now set the gas limit heuristically but without much accuracy, the numbers were taken in a hurry). 

The above would result into getting the transaction pushed out of the transaction pool with a failure status.

This all though would also last a very long time. In the extreme, I think, it could be days.

Now here we have a need for a consideration.

First: with #523 there was a new pending payable scanner introduced. It scans in intervals and can determine the amount of time elapsed since the transaction left the Node. Because I though a limit closing anything pending too long would be favorable I implemented it and set to 6 hours because I really didn't know what number it should be. 

Given the previous there is now a conflict, if we decide to continue having a strict time out limit, this issue and this card may evaporate, if we want to untie the limitation, we may need this specific failure resolution to be in.      

If yes, there is a general way to do that, you just need to look at a receipt of the given transaction and if its status marks a failure we should first look at the gas consumed and if the amount equals to the gas limit we provide with the transaction we know that the cause of the failure was running out of gas.

**Comment by kauri-hero** [comment]
It would be good to discuss this card as a group since EIP-1559 was implemented on Polygon which now provides a more reliable way to estimate gas, and also stands to reduce gas costs under most circumstances.

I think one approach might be to modify the gas-price to be a default value if for some reason the blockchain bridge times out or is inaccessible for receiving a response.
In addition we could re-factor the sending of debt payments to first call the eth_estimategas, which will provide the estimation of gas required, and can also be used to ensure that the consuming wallet has enough gas to execute the transaction

https://docs.alchemy.com/alchemy/apis/polygon-api/eth_estimategas

**Comment by anonmate** [comment]
Agreed with @kauri-hero! If we can have node automatically set gas price to the expected rate, and fallback to a default value – that should hopefully be relatively failsafe. And, if it fails or stays pending for too long, we can cancel the transaction and resend it with a new est gas price.

6 hours seems way too long though, average transaction time on polygon is seconds, on ETH I'm guessing it can be as long as 30mins
