### ISSUE TITLE
Custom data directory doesn't get chain specific folders

### ISSUE THREAD

**Issue by bertllll** [MASQ-Project/MASQ-Node-issues#580]
Although self-generated path for the data directory gives you a new folder for each chain and thus each database and other stuff, if you specify your own idea of data directory it will always point to the same place (folder) regardless what chain is set. 

This is an issue, it doesn't allow you to have your special data directory and use ever more than just one chain (unless you always delete the previous data).

The core of the problem probably lies in `data_directory_from_contex()`.

**Comment by dnwiebe** [comment]
![image](https://github.com/MASQ-Project/Node-issues/assets/714105/516f0fad-cdd5-496d-9546-c148575a4ad8)

**Comment by czarte** [comment]
Using any kind of UI forces you to comply with our standard naming of the last level of `data-directory` path. That must be provided with the name of the chain, otherwise, the UI will correct your path. Only the case you start the Node as a service from the command line takes the parameter `--data-directory` as you provide.

## Testing scenario: 

Download new binaries for your system here: https://github.com/MASQ-Project/Node/actions/runs/5725903345 

### Basic Tests for os platforms: Linux, Mac, Windows
1. Use these binaries to run `Daemon` and `command-line UI`.
2. After Deamon startup run command-line UI and change `Chain` with `setup command`. Check the NOTE below the setup list informs you about changing the data directory to match the newly established Chain
3. Change the `data-directory` via UI to a specific user directory e.g.: `/home/username/masq_home` and check the NOTE below the setup list informs you that the data directory matches the specific chain name, therefore the `data-directory` in the setup list should now be ending with the Chain name in the format: `/home/username/masq_home/<chain-name>`.
4. Run the Node with the UI command `start` and ensure there is no panic, or other error corresponding to creating and reading the database. Now you can gracefully shutdown and kill the Daemon.
5. **If you are proficient with setup enviroment variables:** Run the `Daemon` from the command line with `-E` attribute, to load environment variable MASQ_CHAIN to set the right chain-specific directory in the UI setup.

### Advanced Testing for os platforms: Linux & Mac

> For advanced users: Run `Node as a service` from the command line.

1. Run `Node as a service` from the command line with `-E` attribute, to load environment variable MASQ_CHAIN to set the right chain-specific directory for creating and reading the database.
2. Run `Node as a service` from command line with provided `--data-directory` parameter without the chain name on the end e.g.: `/home/username/masq_data_dir` and check that DB is created right in this directory - Node should not add anything into the path you provided with starting the Node.

NOTE: Do not test environment variable MASQ_DATA_DIRECTORY because that variable is not working right now, we know about it and there is a card to fix this bug

NOTE: Do not test "~" tilde in data-directory path. There is a card to be played in regard to remove the bug of ignoring tilde in path.

**Comment by czarte** [comment]
DATA_DIRECTORY_HELP for the Daemon (example directory paths will be replaced with real ones at runtime): 
Directory in which the Node will store its persistent state, including at least its database and by default its configuration file as well. By default, your data-directory is located in your application directory, under your home directory e.g.: '/home/username/.local/share/MASQ/polygon-mainnet'.

In case you change your `chain` to a different one, the `data-directory` path is automatically changed to end with the name of your chain: e.g.: if you choose `polygon-mumbai`, then `data-directory` is automatically changed to: '/home/username/.local/share/MASQ/polygon-mumbai'.

You can specify your own `data-directory` to the Daemon in two different ways: 
1) If you provide a path without the `chain` name on the end, the Daemon will automatically change your `data-directory` to correspond with the chain. For example: '/home/username/masq_home' will be automatically changed to:  '/home/username/masq_home/polygon-mainnet'. 
2) If you provide your data directory with the corresponding chain name on the end, eg: '/home/username/masq_home/polygon-mainnet', there will be no change until you set the `chain` parameter to a different value.

DATA_DIRECTORY_HELP for the Node:
Directory in which the Node will store its persistent state, including at least its database and by default its configuration file as well. Note: any existing database in the data directory must have been created from the same `chain` this run is using, or the Node will be terminated.

[Editor's note: Dan Wiebe was responsible for masticating these messages somewhat under the supervision of czarte.]
