### ISSUE TITLE
Encrypted Data Chunks in Log file

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/MASQ-Node-issues#588]
Under the default `warn` level is showing large amounts of entries of the encrypted data

Additionally, there are occasions where an panic is produced and the UIGateway actor appears to die.

Investigate the source of this:

`2022-06-19T05:26:53.073 Thd20: ERROR: PanicHandler: /Users/runner/work/Node/Node/masq_lib/src/logger.rs:197:43 - UiGateway is dead: SendError::Full(..)
2022-06-19T05:27:33.850 Thd30: ERROR: PanicHandler: src/accountant/mod.rs:937:14 - UiGateway is dead: SendError::Full(..)`

NOTE: @bert suspects it could be related to posting log message to the UI

**Comment by kauri-hero** [comment]
Here is a log file that was observed during a few minutes of consuming:

[Bogus Return Route MASQNode_rCURRENT.log](https://github.com/MASQ-Project/Node-issues/files/8312360/Bogus.Return.Route.MASQNode_rCURRENT.log)

As you can see there are very large lengths of encrypted data being saved to the logs during consuming

**Comment by kauri-hero** [comment]
[db locked - startblock - MASQNode_rCURRENT.log](https://github.com/MASQ-Project/Node-issues/files/8936384/db.locked.-.startblock.-.MASQNode_rCURRENT.log)
[Uploading MASQNode_rCURRENT.log…]()

some logs files showing this

**Comment by dnwiebe** [comment]
Here are the artifacts: https://github.com/MASQ-Project/Node/actions/runs/2549118303

Rudimentary test plan:

1. Do whatever you did before to get annoying ERROR logs containing lots of binary data (in hexadecimal). Verify that the logs you got before are still there, but 1) they're now WARN logs, and 2) they contain no binary data. (There will still be logs with binary data in them, but their level should be lower than ERROR or WARN, so they'll be easy to filter out with `--log-level`.)

2. Do whatever you did before to get the Node to panic because the UiGateway mailbox is full. Verify that it doesn't happen anymore.

That's pretty much it. It's not a big card.
