### ISSUE TITLE
Accountant: No overlapping scans

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#611]
Currently the Accountant will begin a scan whenever it receives instructions to do so, whether those instructions are autonomous or external. If there's already a scan of that type running, this can be disastrous: for example, multiple simultaneous Payables scans can result in creditors being paid multiple times.

Modify the Accountant's scan logic so that the Accountant always knows which scans are in progress, and make it reject any scan directive that would start a scan when another scan of the same type has not yet finished.

Make sure it's impossible for a scan to be aborted in progress without the scans-in-progress logic finding out about it and updating its status.

**Comment by utkarshg6** [comment]
# Testing Outline

## What's added

1. An ability to prevent any overlapping scans, and log them.
2. The code for `Accountant` was refactored. The scans are now handled by a new structure called `Scanners` which is owned by `Accountant`.

## Scan Types

There are three types of scanning processes:

1. `Payable`
2. `PendingPayable`
3. `Receivable`

## Triggers

These scans are triggered in two ways:

1. It can be triggered externally using the UI.
2. When Node starts the three scans are initiated, and are constantly being initiated in an interval of __10 minutes__.

## Test Scenarios

### Test Scenario 1

1. Start the Node, and trigger the scans multiple times in a short period.
2. It'll command the Node to initiate a new scan when a scan is already running.
3. Look at the logs and search for logs of this specific type:
```rust
"{SCAN_TYPE} scan was already initiated at {TIMESTAMP}. Hence, this scan request will be ignored."
```
4. If we're able to see this log for all three scan types, with a timestamp pointing to an instant in the near past. We can be assured that scans are initiated and overlaps are being prevented.

### Test Scenario 2

1. Start the Node and use it under heavy traffic (streaming).
2. Previously, before this card was played the problem was there where scans would happen in a short period of time. Which may even lead to duplicate payments. For example, you may search for `Scanning for payables` in these [logs](https://pastebin.com/9VKcWXfP). You'll see the scans with timestamps that are close to each other.
3. Test whether scans are still happening in a short duration of time or not and also verify if it's leading to duplicate payments.

**Comment by dnwiebe** [comment]
### Test Scenario 3 (failed scans are marked as no longer in progress)
1. Start the Node in such a manner as to be able to watch the logs it writes in real time, but with a bad blockchain URL (so that attempted scans will fail).
2. Observe the Node start and fail each of the three scans.
3. From the UI, direct the Node to conduct each of the three scans again, and note that the Node attempts each kind of scan and fails again. Specifically, if the UI tells you that the scan you're requesting is already in progress and refuses to restart it, you should fail this test.
