### ISSUE TITLE
Combine `ReportXxxServiceConsumed` messages

### ISSUE THREAD

**Issue by dnwiebe** [MASQ-Project/MASQ-Node-issues#613]
Currently, when a CORES package containing a data request is sent over a standard O → A → B → E → X → Y → O three-hop route, the `ProxyServer` will send three messages to the `Accountant`:
1. `ReportRoutingServiceConsumed (A)`
2. `ReportRoutingServiceConsumed (B)`
3. `ReportExitServiceConsumed (E)`

Then, when the response CORES package arrives, the `ProxyServer` will send three more messages:

1. `ReportExitServiceConsumed (E)`
2. `ReportRoutingServiceConsumed (X)`
3. `ReportRoutingServiceConsumed (Y)`

Longer routes will result in more messages.

This exacerbates the problem we're having with the `Accountant` being swamped by an avalanche of messages, especially when the user is downloading a long stream of small packets, like you might see in a  YouTube stream.

Modify the `ProxyServer` and `Accountant` so that before a CORES package is sent and after a CORES package is received, one message containing all the information from the present `ReportXxxServiceConsumed` messages is sent to the Accountant. In the most common case, this should reduce the number of debt-accrual messages the `Accountant` must handle by 67%.

**Comment by bertllll** [comment]
**Test plan**

We just need some consuming and maybe to observe things and assess changes in performance (whether scanning works a bit better).
The objectiveness you could have here are low, there is a way to check that the messages tracking consuming are not divided into many of them as before but now each route (I'm talking about just one half of the whole route, that is from the Originator to the Exit Node and vice versa) is processed by only one message of services consumed.

How to navigate you in this mess? The tricky part is that visually you will see probably as many logs as you used to. The big difference is that not every log message is now also an actor message. And an Actor messages, if in a big count, were exactly what caused us problems. 
Now if I say all services consumed on a single route are aggregated it means they travel with one Actor message. 
However, I've kept the logging we had so we have to think of it as each single accounting of a service has its own log, printed when Accountant receives that Actor message and tries to write the different amounts of consumed MASQ into all respective accounts in the payable table.

The shortest, standard one-way route composes of (Originator - First_routing_node - Second_routing_node - Exit_node).

The message produced in this scenario contains: 
1. Timestamp of the moment we are either about to send a CORES package with our request or the moment when we receive the CORES package hiding the response from the server.
1. Then there is a report with the wallet of the Exit Node, its rate pack and the payload size of the server-client request(or response).
1. Then a report of the second Node, with its wallet, rate pack, and then a report of the third Node, its wallet and rate pack.
1. The last information is the payload size of the CORES package because the relay Nodes process CORES packages rather than the clean data. 

Accountant will receive the message, compute money amounts and will write the data into the database, setting the timestamp, but only if it is a brand new record. Upon updating the last mentioned is considered out. What is important for us, it will seemingly look like your Node processed a couple of messages AGAIN. However that's just a normal course of the procurement of the single message.

There really is a more precise way to prove that. You can notice that the logs have an id at their beginning "MsgId ddd", the 'd's are three digits. That way you can see what messages belong together. 

Frankly said, it's a bit silly, because we could find it out even without the id. You can say that all routing services carried in the single message will speak about the same number of bytes (the CORES package payload size) and you also can say that the exit service always processes as the very first from all those services.         

Hopefully I've given you a modest picture of how things are...
