### ISSUE TITLE
Improve Pending/Failed Payment Reattempt Methods

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/MASQ-Node-issues#618]
This may be considered a continuation of MASQ-Project/Node#96 

Currently it appears that if a payment txn is sent through BlockchainBridge and does not receive a confirmed transaction success response response from the blockchain-service-url, it is reattempted many times in sequence in rapid succession.

this needs to be inspected and considerations made to the design to accommodate the following:
1 - transaction fails due to insufficient gas
2 - latency on the blockchain-service-url
_(may need to check the time-out on the web3 library)_
3 - where many payables transactions are sent in sequence and there is rate-limiting
4 - a network timeout causes the initial attempt to be dropped

**Comment by kauri-hero** [comment]
Here is an example of this occurrence inspecting the Alchemy testing provider dashboard

Example 1 - transactions failing due to insufficient gas:
![image](https://user-images.githubusercontent.com/55721017/180599773-8d9c73a5-4517-42de-b356-0f9efc480a97.png)

many of these are sent within a few seconds

**Comment by kauri-hero** [comment]
Example 2 - all these transactions failed due to rate-limiting by the blockchain service provider:

![image](https://user-images.githubusercontent.com/55721017/180599834-d4b0c5e3-b3f4-4bf1-b45c-af8c888d9be1.png)

These occuring in the same time intervals and from the same wallet in both instances.

**Comment by bertllll** [comment]
This probably should be a sequence of cards. Also one embracing all of those items might work out, even though the previous approach should be of the first choice if found feasible. 

Within this group, I'd like to finish with the desirable funds checks. One is regarding the gas amount in the wallet, the second about the balance of the token. Which is #GH-555 and #GH-554, respectively. 

Ideal solution: start with the larger change of the strategy in which we process gathered payments (if more than one debt to be paid found within a scan). We basically want to make most of the possible help of the web3 library with setting up and signing raw transactions (separately) and the we will join them in an array and execute them all at once via convenient web3 library methods (I've already checked them out, there's no obstacle).

One additional piece of rearchitecture will come with breaking the old pattern with multiple transaction results produced by a call over possibly a plenty of transactions. So Accountant received a set of results with one for each payment. Now it appears to be different, we can accept some of:

a) just one result is returned and thus with whatever failure is encountered, the whole paying process terminates and no payment is sent (at least) within this scan iteration. 

b) we can allow a way where the biggest part of the setup of a single payment can produce errors terminating only the single payment processing, causing memorizing the error and a fail back to be able to start processing another payment requested. 
All successfully prepared transactions will come out and market, while all errors also collected and both types of outcome will travel back to Accountant which will then act accordingly.  

I think i prefer the 'b' despite there is a high risk that a failure from one payment will print into all following payments... 

I also plan on writing it so that if any kind of insufficient balance is detected we won't abort, instead, we process as many payments as we will have the means for. After sending out that amount of them, an error message addressed to the user will be generated.
