### ISSUE TITLE
Optimise routing to reduce DNS resolution 'mark'

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/MASQ-Node-issues#633]
Recent discussions revealed that if an exit node fails to resolve a DNS request from an origin Node, the origin Node will mark that Node as unusable for future routes.
There is no expiry to this 'mark' and may result in eventually all  possible exit routes being reduced because all available Nodes could result in this permanent exclusion.

Consider modifying the routing engine to allow this mark to expiry after some conditions, which could include

- [ ] a simple time expiry (somewhere between 20-30 minutes may be a good place to start)
- [ ] explore a way to note the host that failed, so other requests can be consider (this is likely more complicated and may require a separate card to implement in addition to the above improvement

Comments from @dnwiebe:

> when a DNS resolution fails, we mark the exit Node so that we won't use it again unless no other exit Node works either. (That mark should expire over time, but I don't think it does yet. It also ought to apply specifically to the host that was requested, since that exit Node might be able to contact other hosts; but I know it doesn't do that yet.)

**Comment by dnwiebe** [comment]
Suggestions:
Instead of marking the Node as "undesirable for exit," put a HashMap in the NodeRecordMetadata that is keyed by hostname, where the value is the timestamp of the moment when the Node was found to be useless for exit for that hostname.

This will enable the Router to assign an appropriate negative score to this Node only when it is A) considered as an exit Node B) for the particular host it has failed in the past to contact, and that negative score can be calculated according to how long it has been since it was tried. That way, the penalty can fade over time.

But _do_ we want it to fade over time? If a particular Node can't find our intended server now, is there any reason to believe it will ever be able to find that server in the future? Maybe there shouldn't be any timestamp, and the HashMap should actually be a HashSet working as a straight blacklist.
