### ISSUE TITLE
Automatic Retries for the URLs in case of DNS Resolve Failure

### ISSUE THREAD

**Issue by utkarshg6** [MASQ-Project/MASQ-Node-issues#651]
In case of a DNS Resolve Failure, the user has to manually retry, then Node will try to find different Node that can access the certain URL. This process can be made easier for the user, if the retries are done automatically. 

Once there are automatic retries, it'll cost the user a lot of money because each attempt will cost money. In the worst case, the user can enter a broken URL and might loose all the money. This problem can be prevented if we limit the automatic retries, maybe by using a hard limit for number of attempts.

Dan & Bert Comments:

Could hard code at 3 perhaps, and see if that is good enough for user

if this is a runtime changeable option, it will be more difficult to complete (set-configuration)

**Comment by dnwiebe** [comment]
Opinion: This option (number of retries) should be hard-coded first; then there should be two more cards (as necessary) to make it configurable from the command line and storable in the database.

Also, the number of possible exit Nodes depends on the min-hops value. We experimented with min-hops counts of 2, 3, and 4 and found a tentative relationship: exit-Node count = (min-hops - 1) * 4. A retry count greater than the number of exit Nodes (minus one, since we don't count the original attempt in the number of retries) is wasteful, since it would try exit Nodes that had already failed. A decision about retry counts lower than the number of exit Nodes would depend on cost.

If we're fairly sure we'll have this configurable by the time people start using it for real, it doesn't matter what our hard-coded value is, because nobody will ever pay real money for it.

**Comment by Syther007** [comment]
Review this comment when doing user testing
https://github.com/MASQ-Project/Node/pull/326/files/477ab06477d1d68fb7424f7cc8753d52b5305bf8#r1299983055

**Comment by Syther007** [comment]
**Testing Outline**
maximum retries before DNS Failure is 3

- **Test Automatic Retries** 
- Find a way to simulate a DNS Failure and then a success.
- Find a way to simulate 2 DNS Failures and then a success.
- Ensure normal browsing is unaffected
- Consider the time it takes for a complete DNS fail (Failed 3 times)

**Idea on how to simulate a DNS failure.**
Create a test network 
1 or more exit nodes with cheep rate packs and a broken DNS (Maybe loopback address) 
Test rest of the nodes will have the default rate pack and a working DNS

Bad DNS Node -- Bad DNS Node -- Good DNS Nodes


Check error output in a browser a couple of times, make sure it's friendly enough for a real user to see. do this for both `HTTPS` & `HTTP`


**Log entries to look out for.**
`Successful attempt of DNS resolution, removing DNS retry entry for stream key`
`Retiring stream key`
`No DNS retry entry found for stream key:`
