### ISSUE TITLE
User's control over `start_block`

### ISSUE THREAD

**Issue by bertllll** [MASQ-Project/MASQ-Node-issues#766]
I noticed of inconsistency at our exposer of the start_block parameter to the user. While there are places where we give him a chance to affect the value there are also such where we omit this parameter among the others that can be set. 

We allow it to be changed at runtime by the `set_configuration_command`, but we don't in the API of the Daemon. This parameter is mentioned nowhere in the `setup_reporter`, the heart of the `setup` command of the Daemon.

Should we allow it everywhere or nowhere, or even just somewhere? Why? Investigate.

**Comment by dnwiebe** [comment]
The user should probably not be allowed to set the `start_block` arbitrarily. This card should be either about removing `start_block` from the command line and the `set_configuration` command and the `clap` schema and so on (but not from the CONFIG table), or it should be about replacing it with some sort of `reset_start_block` parameter/command/schema that throws out the `start_block` information in the CONFIG table so that it will be recomputed when the Node next starts. Which of those we do should probably be a KauriHero question.

**Comment by dnwiebe** [comment]
After a few discussions in the daily meeting, we have been unable to come up with any reason to keep the `start-block` parameter accessible by the user at all. It should be completely removed from both the `setup` and the `setConfiguration` commands, and set only by the BlockchainBridge after it investigates the blockchain itself.

As for whether it should be resettable to nothing by the user...that's still a @kauri-hero question.

**Comment by kauri-hero** [comment]
Agreed @dnwiebe @bertllll - it does seem that there isn't a use-case for user to be able to config the `start_block` parameter.
If a user was motivated enough, they could go into the sqlite3 database and edit the value of `start_block` to `null` to reinitialize a full block range scan.
